### ISSUE TITLE
Одновременное включение двух аксессуаров.

### ISSUE THREAD

**Issue by 1swertwr** [AlekseevAV/homebridge-noolite#1]
При одновременном включении двух аксессуаров, в приложении Дом оба отображаются как включенные. По факту происходит включение только одного. Лог ниже.

Mar 15 18:29:59 raspberrypi homebridge[2246]: [2018-3-15 18:29:59] [NooLitePlatform] Прихожая (suSwitch-) Set On characteristic to true
Mar 15 18:29:59 raspberrypi homebridge[2246]: [2018-3-15 18:29:59] [NooLitePlatform] Столовая (suSwitch-) Set On characteristic to true 
Mar 15 18:29:59 raspberrypi homebridge[2246]: [2018-3-15 18:29:59] [NooLitePlatform] Прихожая (suSwitch-) message written in SET callback: NooLiteRequest { 
Mar 15 18:29:59 raspberrypi homebridge[2246]: ch: 15, Mar 15 18:29:59 raspberrypi homebridge[2246]: cmd: 2, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: mode: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id0: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id1: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id2: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id3: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: idBytes: [ 0, 0, 0, 0 ], 
Mar 15 18:29:59 raspberrypi homebridge[2246]: st: 171, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: ctr: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: res: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: fmt: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d0: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d1: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d2: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d3: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: sp: 172 } 
Mar 15 18:29:59 raspberrypi homebridge[2246]: [2018-3-15 18:29:59] [NooLitePlatform] Столовая (suSwitch-) message written in SET callback: NooLiteRequest { 
Mar 15 18:29:59 raspberrypi homebridge[2246]: ch: 11, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: cmd: 2, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: mode: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id0: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id1: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id2: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id3: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: idBytes: [ 0, 0, 0, 0 ], 
Mar 15 18:29:59 raspberrypi homebridge[2246]: st: 171, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: ctr: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: res: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: fmt: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d0: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d1: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d2: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d3: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: sp: 172 } 
Mar 15 18:29:59 raspberrypi homebridge[2246]: [2018-3-15 18:29:59] [NooLitePlatform] Прихожая (suSwitch-) read data by CHANNEL: NooLiteResponse { 
Mar 15 18:29:59 raspberrypi homebridge[2246]: ch: 15, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: cmd: 2, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: mode: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id0: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id1: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id2: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: id3: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: idBytes: [ 0, 0, 0, 0 ], 
Mar 15 18:29:59 raspberrypi homebridge[2246]: st: 173, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: ctr: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: togl: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: fmt: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d0: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d1: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d2: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: d3: 0, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: crc: 190, 
Mar 15 18:29:59 raspberrypi homebridge[2246]: sp: 174 }

**Comment by AlekseevAV** [comment]
С версии 0.0.17 реализован механизм очередей запросов/ответов MTRF адаптера, который решает данную проблему.
