### ISSUE TITLE
Опрос мудуля через API

### ISSUE THREAD

**Issue by algar42** [AlekseevAV/homebridge-noolite#10]
Использую вызов api "http://ip:port/api/channels/x/acc" в цикле по устройствам SLF чтобы получать их актуальный статус раз в минуту. Через какое-то неопределенное время ответ от модулей перестает приходить. Т.е. в вебинтерфейсе модуля в логе ответа нет и опросить статус канала уже нельзя. Управление при этом работает. Т.е. MTRF-64 комманды отрабатывает, но ответ от блока где-то теряется. 
Если вызовы к API не делать, то все работает стабильно. В чем беда разобраться не могу....

**Comment by AlekseevAV** [comment]
Очень похоже на проблему, которая на данный момент находится в работе - через некоторое время (3-4 дня использования) от адаптера перестают приходить какие-либо сообщения. В последних версиях был добавлен реконнект к адаптеру, если он перестает отвечать, однако проблему это не решило.

Сложность в том, что пока не смог 100% воспроизвести подобное поведение локально. Если у вас есть последовательность действий, которая гарантированно приводит к описанным проблемам, то напишите ее.

**Comment by algar42** [comment]
Пока есть только догадки:
1. Вы говорите 3,4 дня. Но если я делаю опрос ежеминутно, то ответ перестаёт приходить уже через два, три часа. Тесть это поведение предположительно зависит от количества полученных статусов. Куда сохраняются полученные от мтрф посылки? Может переполняется буфер сообщений? Реконнект к блоку безполезен т.к. по диодам на модуле видно, что он отвечает на запрос. Сообщение теряется уже где-то в программе.
2. Я не гуру, но возможно было-бы неплохо лочить порт под процесс. (создавать .lck файл чтобы система знала что порт занят)
3. Такое же поведение я наблюдаю если запустить любое терминальное приложение типа minicom на том же порту. Когда терминал активен в нем видны запросы к мтрф, но ответа нет не в терминал не в веб интерфейс программы. Стоит закрыть minicom и все нормализуется.

Пока все мои наблюдения. Может наведёт на мысли. А я буду наблюдать дальше

**Comment by algar42** [comment]
провел эксперимент. Опрос одного канала с интервалом две секунды. Ответ переставал приходить два раз на 959 запросе и один раз на 966м. 
Т.е. явно количество запросов играет роль в этом глюке..

**Comment by AlekseevAV** [comment]
У меня были подозрения на счет этого, хотел сделать примерна такой же тест, но вы меня опередили.
Попробую вечером локально воспроизвести и понять в чем именно проблема.

**Comment by algar42** [comment]
Увеличил интервал опроса до 10 секунд, и опять стоп на 959м запросе. т.е. и интервал не играет роли.

**Comment by AlekseevAV** [comment]
На выходных удалось воспроизвести проблему. Ошибки начинали сыпаться примерно на том же количестве запросов, что и у вас (около 1000).
Сделал небольшой фикс, после чего проблема у меня перестала воспроизводиться. 10000 запросов было обработано успешно, без зависаний.
Можете обновиться из master ветки или ближе к вечеру планирую залить новую версию (0.1.1), которую через npm можно будет обновить.

**Comment by algar42** [comment]
Сейчас обновлюсь и погоняю. Спасибо!!!!

**Comment by algar42** [comment]
Прошло 8000 опросов. Все работает как часы. Спасибо!
Проблему закрываю.
