### ISSUE TITLE
Статус

### ISSUE THREAD

**Issue by sclk34** [AlekseevAV/homebridge-noolite#11]
Добрый день. Не могу получить статус привязанного устройства noolite-f json командой. Возвращается только {status ok}. Но окне лога виден полный статус устройства. Такого функционала нет? Хотел бы получать состояние устройства (вкл/выкл и т.п.) через json.
Так же почему то не отображаются привязанные к MTRF устройства noolite1. Устройства привязывались ранее, не через ваш проект.

Спасибо заранее за ответ.

**Comment by AlekseevAV** [comment]
Добрый вечер!
А каким запросов вы статус устройства пытаетесь получить?

Из-за технической реализации MTRF и протокола NooLite первой версии (которая без индекса F) нельзя каким-либо образом узнать о привязанных устройствах. Адаптер их не сохраняет у себя в памяти. Как раз с выходом NooLite-F протокола ситуация поменялась и при работе с ним мы видим все привязанные устройства и их каналы.

**Comment by algar42** [comment]
попробуйте http://192.168.9.6:8080/api/channels/10/acc

**Comment by AlekseevAV** [comment]
Закрываю, так как больше этот момент вопросов не вызывал.
