### ISSUE TITLE
Очень жду поддержки SRF 10-1000

### ISSUE THREAD

**Issue by rmnvlkv** [AlekseevAV/homebridge-noolite#15]
Очень жду поддержки этого переключателя

**Comment by yarry** [comment]
У меня заведён как 10 slf блоков.

**Comment by AlekseevAV** [comment]
В итоге пришли к мнению, что SRF 10-1000 не имеет каких-либо программных отличий от обычных SLF блоков. Привязка к адаптеру и создание новых устройств в HomeKit идет также для каждого из его каналов отдельно, как и с отдельными SLF блоками, поэтому смысла в добавлении отдельного SRF 10-1000 устройства пока не вижу.
