### ISSUE TITLE
Автоматика ворот 

### ISSUE THREAD

**Issue by rmnvlkv** [AlekseevAV/homebridge-noolite#16]
SLF снят с производства, как думаете чем теперь можно реализовать открывание закрывание ворот ... чтобы замыкалась цеп на 1 секунду

**Comment by AlekseevAV** [comment]
Хмм... Нужно подумать. Давайте вот тут этот вопрос обсудим - tg://t.me/Noolite

**Comment by AlekseevAV** [comment]
У NooLite появился блок как раз для управления подобными устройствами - https://www.noo.com.by/silovoj-blok-srf-1-1000-r.html
Сейчас опубликовал версию 0.2.0, в которой добавил поддержку этих устройств. В принципе этот блок можно откалибровать, чтобы он подавал сигнал на одну секунду. К сожалению, его нет в наличии, поэтому не могу сам попробовать.

**Comment by 1swertwr** [comment]
Вместо блока SLF можно использовать SUF.
