### ISSUE TITLE
Запоминание уровня яркости блоками SUF

### ISSUE THREAD

**Issue by 1swertwr** [AlekseevAV/homebridge-noolite#18]
Если на блоке SUF  установлено значение яркости >0- 100<, то после выключения и включения снова, значение будет =100, а должно быть, ранее установленное.

Чтобы значение при включении было равным, установленному, до выключения необходимо передавать команду CMD =2 или CMD = 4 --- без аргументов.

**Comment by AlekseevAV** [comment]
Разобрались с этой проблемой.
Она связана со спецификой работы NooLite-F диммируемых блоков и HomeKit.
Алгоритм работы:

1. Через HomeKit включаем блок и задаем ему яркость 50% -> в noolite уходит 6 команда (задать яркость) с соответствующим значением
2. Выключаем блок (не изменяя его яркость) -> в noolite уходит команда 0 (выключить), а в ответ приходит 130 команда (статус блока), в котором яркость имеет значение **0**. Вот в этом и заключается проблема, так как данная команда интерпретируется, как **актуальное** состояние блока и, соотвественно, HomeKit запоминает "новое" значение яркости как 0 (однако в блоке хранится его старое значение в 50%).
3. Включаем блок (не изменяя яркость) -> в noolite уходит команда 2 (включить), и, так как HomeKit помнит, что у этого устройства последнее состояние яркости было 0, то он автоматом шлет вторую команду "задать яркость 100%", тем самым сбрасывая яркость на блоке на 100%.

Обсудили, что возможно в следующих прошивках блоков данный момент будет исправлен производителем и блок будет всегда отдавать актуальное значение яркости, которое он помнит. Пока данную проблему закрываю.
