### ISSUE TITLE
Поддержка nodejs 12

### ISSUE THREAD

**Issue by iShift** [AlekseevAV/homebridge-noolite#20]
Не работает на nodejs 12

**Comment by AlekseevAV** [comment]
А какая ошибка падает? Она именно с плагином связана? На чистую систему ставили или обновляете?

**Comment by AlekseevAV** [comment]
Возможно проблема была с https://github.com/serialport/node-serialport, которую мы используем для взаимодействия с последовательным портом.
Обновил ее в зависимостях до актуальной версии - 8.0.7. В ней уже должна быть поддержка Node 12. У меня локально под Node 12 запустилось корректно, ошибок не было.

Обновил версию плагина до 0.3.3.

**Comment by iShift** [comment]
После обновления все ок, спасибо!
