### ISSUE TITLE
Автоматизация "Гигростат"

### ISSUE THREAD

**Issue by 1swertwr** [AlekseevAV/homebridge-noolite#3]
Автоматизация "гигростат". 
Создана автоматизация, которая по достижении заданного значения влажности, полученного от датчика PT111, включает вентилятор.

Теоретически срабатывает в 100%
- в программе ДОМ, вентилятор отображается как включенный
- по факту вентилятор не работает
Есть предположение, что такое поведение связано с багами, описанными выше.
Лог предоставить пока не получается.

**Comment by AlekseevAV** [comment]
Да, проблема дублируется в #1
