### ISSUE TITLE
"Залипание"

### ISSUE THREAD

**Issue by 1swertwr** [AlekseevAV/homebridge-noolite#4]
Иногда происходит"залипание" аксессуара (тип garageDoorSlf) при обновлении в Дом.
Никаким образом не удается его вывести из этого состояния. 
При этом, остальные аксессуары продолжают работать.
В логах ничего нет.
Помогает только рестарт сервиса.

**Comment by AlekseevAV** [comment]
Вот тут починил: https://github.com/AlekseevAV/homebridge-noolite/commit/a827ef159bd64f02cede77eca8dfce8094d2d315. Если в версиях свежее 0.0.18 такое повторится, то перекройте данное обсуждение.
