### ISSUE TITLE
Timeout to get response from MTRF

### ISSUE THREAD

**Issue by SEVSM** [AlekseevAV/homebridge-noolite#6]
Здравствуйте. Установил homebridge-noolite, при попытке отправить какую-либо команду выдает error: Timeout to get response from MTRF. У меня MTRF-64 UART, в config.json прописан "serialport": "/dev/ttyAMA0". Нужно ли ли какой-либо еще отдельный драйвер для  MTRF-64 UART устанавливать? В чем может быть причина ошибки? Буду благодарен за любую помощь, очень хочется привязать noolite к homebridge.

**Comment by AlekseevAV** [comment]
Здравствуйте.
После запуска Homebridge с данным плагином, он (плагин) должен попытаться подключиться к MTRF адаптеру по порту, указанному в конфиге (serialport). По результату этой операции он должен вывести сообщение со статусом подключения:
`Sucess connect to NooLite MTRF`
или
`Cannot connect to NooLite-MTRF`

Какой-то из этих статусов в консоли есть?

**Comment by SEVSM** [comment]
Да, есть первый статус. Но когда с web интерфейса подаю команды, пишет error. Кстати, на MTRF должен мигать диод, когда на него подаются команды? У меня не мигает...




Отправлено из мобильной Почты Mail.Ru


суббота, 21 апреля 2018 г., 18:31 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by AlekseevAV** [comment]
Да, должен мигать. А какую команду передаете?
И, чтобы убедиться в работоспособности адаптера, можно через NooLiteOne попробовать отправить команду.

**Comment by SEVSM** [comment]
Команду привязки например. Noolite_one на windows ставится, у меня нет переходника с UART на usb. Но при загрузке raspberry на MTRF однократно мигает желтый диод. Скорей всего адаптер рабочий. Проблема точно не в установке каких либо ещё драйверов для MTRF на Raspberry?

**Comment by AlekseevAV** [comment]
Нет, дополнительно драйвера ставить не нужно.
А какой блок NooLite привязываете? И какую именно команду в веб интерфейсе формируете?
В зависимости от типа NooLite устройства (силовой блок/датчик, NooLite-F или старый протокол) нужно формировать разные команды привязки.

**Comment by AlekseevAV** [comment]
Отлично! Не за что.
Сегодня еще выпустил пару патчей и доработок, так что в любом случае обновите плагин до последней версии.
