### ISSUE TITLE
Диммирование 

### ISSUE THREAD

**Issue by SEVSM** [AlekseevAV/homebridge-noolite#7]
Добрый день. А когда планируете  добавить поддержку SUF блоков? И ещё, недавно приобрел SUF блок, привязал как обычный SU (с диммированием), но с HomeKit яркость не регулируется, в HomeKit появляется статус «обновляется», а в консоли через какое-то время появляется Timeout to get response from MTRF. В чем может быть проблема?

**Comment by AlekseevAV** [comment]
Добрый день!

Поддержка SUF блоков (и ряд других доработок) будет реализована в одной из следующих версий плагина (начало мая).

По поводу блока SU - как раз в одном из последних обновлений плагина фиксил этот баг. Он заключался в том, что при регулировках яркости в приложении Дом, HomeKit генерировал очень много практически одновременных запросов, которые MTRF адаптер не мог обработать из-за его технических ограничений. В последней версии была добавлена задержка в 250мс между отправками команд на адаптер. 250мс - это минимальное значение, при котором адаптер способен нормально обработать все команды от HK. Так что обновляйтесь и тестируйте.

**Comment by SEVSM** [comment]
Обновление пока не ставил, наверное в этом и есть проблема, на майских испытаю, хотя к этому времени, надеюсь,  может уже появится поддержек SUF)) Спасибо за поддержку!

**Comment by SEVSM** [comment]
Добрый день. Скажите, пожалуйста, в ближайшее время планируется доработка модуля для корректной работы с SUF блоком в режиме noolite-f (cм. комментарий выше)?

**Comment by AlekseevAV** [comment]
Добрый день.
Проблема в том, что у меня сейчас нет под рукой SUF блока и я не могу протестировать работу плагина с ним.  В ближайшее время он должен до меня дойти и тогда смогу потестить и устранить найденные баги.

**Comment by SEVSM** [comment]
Спасибо! Будем ждать...

**Comment by SEVSM** [comment]
Добрый день. Александр, подскажите, как с вами связаться вне форума? Есть интересное предложение. Моя почта evgeny_smorchkov@mail.ru

**Comment by iShift** [comment]
@SEVSM https://t.me/Noolite

**Comment by AlekseevAV** [comment]
Забыл написать здесь о том, что ответил на почтовый ящик.

> https://t.me/Noolite

Но это тоже хороший вариант.

**Comment by AlekseevAV** [comment]
Диммирование доработано в 0.0.28 версии
