### ISSUE TITLE
Датчик DS-1

### ISSUE THREAD

**Issue by 1swertwr** [AlekseevAV/homebridge-noolite#8]
При перезагрузке Raspberry датчики DS-1 всегда в состоянии - "ОТКРЫТО"
Homebridge не помнит предидущее состояние датчиков DS-1

**Comment by AlekseevAV** [comment]
В коде мы нигде состояние при запуске не устанавливаем, так что это видимо где-то кешируется - либо в HomeKit, либо в homebridge. Актуальное состояние нам не получить, так как NooLite не поддерживает опрос датчиков.
Можно только добавить жесткое указание состояние датчика при его инициализации (к примеру ставить состояние "ЗАКРЫТО"), если это решит проблему.
